### ISSUE TITLE
Can't tell whether there was a response to a command

### ISSUE THREAD

**Issue by sde1000** [onitake/daliserver#1]
The network protocol for daliserver doesn't allow it to indicate whether or not a command returned a response.  Lack of response to a command is reported as response 0xff, status 0, which is the same as a response of 0xff.

This makes some DALI commands impossible to use.  For example, I can happily use the "QUERY ACTUAL LEVEL" command and receive valid data back because this command always causes a response from the ballast.  I can't use the "QUERY LAMP FAILURE" command because this command causes a response of 0xff for "yes" and a lack of response for "no" — daliserver squashes both of these to a response of 0xff.

In lib/usb.c you distinguish between the two cases, but you just call dali->req_callback() with a hard-coded 0xff when you're dealing with USBDALI_TYPE_NO_RESPONSE; a fix for this ought to be fairly simple.  The problem (and the reason I'm not sending a patch) is that the network protocol will have to be changed to fix this and I don't want to pre-empt whatever change you decide to make.

**Comment by onitake** [comment]
Thanks for pointing this out.
I've always been aware that the (very simplistic) protocol wouldn't stand the trial of time, but it was sufficient for the simple dimming control I use it for.

If it can make daliserver useful for you, I'll review and improve the protocol and condition handling.

**Comment by sde1000** [comment]
That would be great!

If it won't affect your use of it, I suggest redefining the "status" byte of the response so that success/failure is reported in bit 0, and response or lack of response is reported in bit 1.  So we get:

| Status | Meaning |
| --- | --- |
| 0 | success, no response (the most common case) |
| 1 | failure |
| 2 | success with response |

**Comment by onitake** [comment]
I've improved the network protocol and added more status codes so you can differentiate the different types of messages. The Perl examples are updated as well and should be ready to go.

If you can test the changes, please report your results. I haven't had time for that yet.

**Comment by sde1000** [comment]
Ok, that appears to work so far.  I get sensible replies to QUERY LAMP FAILURE.

I think it would be useful to expand the protocol further, though: it's able to report commands that originate on the DALI bus, but there's nowhere for it to indicate whether those commands had a response and what that response was.  I believe the hardware is capable of reporting responses to observed commands, because the manufacturer provides a DALI bus snooping application that does it.

**Comment by onitake** [comment]
I'll think about the proposed changes. Ah, what I'd give for proper documentation...

As for this bug report, I'll close it for now, since the feature seems to be working.
