### ISSUE TITLE
Updated Mas OS kext

### ISSUE THREAD

**Issue by ben-knt** [onitake/daliserver#11]
The dummy kext wasn't allowing me to claim the device on Mac OS El Capitan 10.11.2.

I updated the plist with kpi libraries but -- in the end -- it was essential to declare IOProviderClass as IOUSBDevice and not IOUSBInterface. Please note the libkern library could likely be sent back a few versions. Importantly, the attached is unsigned so SIP must be disabled to use it.

[Info.plist.txt](https://github.com/onitake/daliserver/files/101107/Info.plist.txt)

**Comment by onitake** [comment]
Thanks a lot. I haven't tested on OS X in a long time.
I know someone who has a kernel extension code signing certificate, so I was planning to ask them to sign the kext for me. I'll do that once I've had a chance to test your changes.
Looks like github messed with the formatting, can you create a gist instead?

**Comment by ben-knt** [comment]
You're welcome. Here's the gist, hope it's better. https://gist.github.com/ben-knt/3332c930c04e4892bef2

**Comment by ben-knt** [comment]
By the way, I went through the Perl scripts and have some comments. Lampoff.pl crashes daliserver... for what reason, I don't know? I'm happy to help find out why. We can discuss offline sometime if you would like.

**Comment by onitake** [comment]
Uh, what?
I know that `usbdali.pm` is a bit buggy and doesn't return the response correctly. I fixed that problem locally, but haven't pushed it to github yet.

Are you positive it crashes daliserver?

**Comment by onitake** [comment]
Ok, fixed `usbdali.pm` in bae41b12.

**Comment by ben-knt** [comment]
I pulled in the changed file but no change. Lampoff.pl successfully turns off a lamp but the server crashes after.  Two commands issued below:
 
Braque:perl benknuth$ perl allset.pl 255
Writing 4 bytes to socket, address=254 command=254
Received status:success response:0
Braque:perl benknuth$ perl lampoff.pl 12
Writing 4 bytes to socket, address=25 command=0
Braque:perl benknuth$ 


[2016-00-22 20:28:13] INFO Starting daliserver
[2016-00-22 20:28:13] INFO Server ready, waiting for events
[2016-00-22 20:28:32] INFO Got connection from 127.0.0.1:27089
[2016-00-22 20:28:32] INFO Got frame: 0x02 0x00 0xfe 0xfe
[2016-00-22 20:28:32] INFO Enqueued transfer (0x7fb7abc06cc0,0x7fb7abc06a90)
[2016-00-22 20:28:32] INFO Sending data to device:
0x00000000 12 01 00 03 00 00 fe fe 00 00 00 00 00 00 00 00 ................
0x00000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Direction: USB<->DALI Sequence number: 01 Type: 16bit DALI Address: fe Command: fe 
[2016-00-22 20:28:32] INFO Received data from device:
0x00000000 12 73 00 00 fe fe ff ff 01 00 00 00 00 00 00 00 .s..............
0x00000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Direction: USB<->DALI Type: Send complete Address: fe Command: fe Status: ffff 
[2016-00-22 20:28:32] INFO Received data from device:
0x00000000 12 71 00 00 00 00 00 8a 01 00 00 00 00 00 00 00 .q..............
0x00000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Direction: USB<->DALI Type: Send response Response: ff Status: 008a Sequence number: 01 
[2016-00-22 20:28:32] INFO Response to (0x00 0x00): 0xff [0x008a]
[2016-00-22 20:28:32] INFO Connection 9 was disconnected
[2016-00-22 20:28:32] INFO Closing connection 9
[2016-00-22 20:28:45] INFO Got connection from 127.0.0.1:27345
[2016-00-22 20:28:45] INFO Got frame: 0x02 0x00 0x19 0x00
[2016-00-22 20:28:45] INFO Enqueued transfer (0x7fb7abe01520,0x7fb7abe03090)
[2016-00-22 20:28:45] INFO Connection 9 was disconnected
[2016-00-22 20:28:45] INFO Closing connection 9
[2016-00-22 20:28:45] INFO Sending data to device:
0x00000000 12 02 00 03 00 00 19 00 00 00 00 00 00 00 00 00 ................
0x00000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Direction: USB<->DALI Sequence number: 02 Type: 16bit DALI Address: 19 Command: 00 
[2016-00-22 20:28:45] INFO Received data from device:
0x00000000 12 73 00 00 19 00 ff ff 02 00 00 00 00 00 00 00 .s..............
0x00000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Direction: USB<->DALI Type: Send complete Address: 19 Command: 00 Status: ffff 
[2016-00-22 20:28:45] INFO Received data from device:
0x00000000 12 71 00 00 00 00 00 8a 02 00 00 00 00 00 00 00 .q..............
0x00000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Direction: USB<->DALI Type: Send response Response: ff Status: 008a Sequence number: 02 
[2016-00-22 20:28:45] INFO Response to (0x00 0x00): 0xff [0x008a]
[2016-00-22 20:28:45] **ERROR** Error writing 4 bytes to connection 2059272945: Bad file descriptor
Segmentation fault: 11
Braque:~ benknuth$

**Comment by onitake** [comment]
Ouch!
I'll look into this right away. It's clear that the connection is killed before the response can be sent, as some of the Perl scripts don't read the response at all. But the crash is in no way ok!

Can you run daliserver in gdb and produce a backtrace?

**Comment by ben-knt** [comment]
Here's the backtrace. Hope this helps! 
<script src="https://gist.github.com/anonymous/bced4b4bc594748b0d3f.js"></script>

These two commands sent were: 
perl lampset.pl 12 255
Writing 4 bytes to socket, address=24 command=254
Received status:success response:0
perl lampoff.pl 12
Writing 4 bytes to socket, address=25 command=0

**Comment by onitake** [comment]
Umm... I didn't get your backtrace. Did you forget the link?

But no matter, I found the bug. It's just a bit hard to fix. Need to think about it some more.

As a temporary workaround, I pushed a modified lampoff.pl that checks the server response. This should prevent the crash.

**Comment by onitake** [comment]
I moved the crash report into a new issue #12, please post there.

**Comment by onitake** [comment]
To get back to the issue, can you change com.apple.kernel.libkern back to 1.8 and see if it still works on your system?

**Comment by ben-knt** [comment]
Changed it back and it works with no apparent problems.

**Comment by onitake** [comment]
Sorry, I completely missed your message.
I'll commit the updated Info.plist then.
