### ISSUE TITLE
usb error

### ISSUE THREAD

**Issue by pusuarigth** [onitake/daliserver#13]
when I try to run daliserver on debian64 compiled from git clone i get:
DALI USB multiplexer (daliserver)
Copyright (c) 2011 onitake All rights reserved.

[2016-05-08 12:44:11] INFO Starting daliserver
[2016-05-08 12:44:11] **ERROR** Error opening USB device: Access error
[2016-05-08 12:44:11] **ERROR** Can't find USB device
[2016-05-08 12:44:11] INFO Exiting

The DALI usb is working on the windows side on DaliCopckit ,

On lusb 
the dali usb from tridonic is listed as :
< Bus 003 Device 008: ID 17b5:0020

Thank's for reading

**Comment by onitake** [comment]
Sorry for the late response.

This looks like a permission problem. Either run daliserver as root or add udev rules to allow user access.
Try these instructions on how to to accomplish this: http://unix.stackexchange.com/questions/44308/understanding-udev-rules-and-permissions-in-libusb

**Comment by pusuarigth** [comment]
hi again thanks for answering Ii tried  but no luck

sudo daliserver
DALI USB multiplexer (daliserver)
Copyright (c) 2011 onitake All rights reserved.

[2016-05-20 16:30:24] INFO Starting daliserver
[2016-05-20 16:30:24] **ERROR** Error setting configuration: Busy
[2016-05-20 16:30:24] INFO Exiting

I dont need a dali server I just wanted to run the code to and see how a Dali Device scan works. I am not sure this project has this function implemented..

**Comment by sde1000** [comment]
This project is a device driver that exposes a Tridonic DALI-USB as a network service.  It doesn't have any DALI device scanning code in it.

You can find code that makes use of this driver to scan for DALI devices at https://github.com/sde1000/python-dali

You won't be able to use it unless you get daliserver to talk to the DALI-USB, of course.

**Comment by onitake** [comment]
@pusuarigth I recommend recompiling daliserver with debug logging (`./configure --enable-debug`) and running daliserver with debug output turned on (`daliserver -d debug`).
This should give you more information on why it can't access the device.

But if you just want to know how device scanning works, I recommend either reading the specs or follow @sde1000 's advice and read the python-dali source code. [examples/find_ballasts.py](https://github.com/sde1000/python-dali/blob/master/examples/find_ballasts.py) should contain what you need.

**Comment by pusuarigth** [comment]
I was using it from windows side that has a DaliBusserver v3.1. 2 from Tridonic, I wanted to test it on the other side ;) using this project, I will take a look at the code thanks.

**Comment by onitake** [comment]
As the issue seems to be out of scope, I'm closing it now.
