### ISSUE TITLE
pack/unpack bug

### ISSUE THREAD

**Issue by choka85** [onitake/daliserver#16]
in pack.c in pack/unpack functions in. PACK_UBYTE/PACK_BYTE case u need to define "value" as a 1 byte variable e.g.:
unsigned char value = va_arg(args, unsigned int); instead of
unsigned int value = va_arg(args, unsigned int);
Same applies for PACK_USHORT (unsinged short value = ...)
In those cases u write 4 bytes instead of 1/2 in each of fields of "UsbDaliIn in;" structure.. For PACK_UBYTE on little endian architectures LSB is 1st byte so it works "ok", with zeroing additional 3 bytes, but on big endian architecture u actually overwrite 4th byte with usable data, while zeroing first 3..

Otherwise, awesome work!

Regards,
Goran

**Comment by onitake** [comment]
Oops, that was a bad oversight on my part.
Will be fixed ASAP.

Thanks for reporting!

**Comment by onitake** [comment]
I looked at the problem and it seems to be mainly in `unpack()`.
`pack()` uses unsigned int only locally (it's the smallest type va_args supports), but `unpack()` interprets each argument as a pointer; and there it doesn't make much sense to use `int *`.
I need to verify how much impact changing it will have first, but expect a patch soon.

**Comment by onitake** [comment]
Can you test the latest master?
This should fix your issue.

**Comment by choka85** [comment]
True.. Issue i noticed was in unpack only.. i wrongly assumed that same applies for pack also.. Looks good now... Thx..

**Comment by onitake** [comment]
I also updated the test case for pack/unpack, please run `make check` and see if it succeeds on your system.
