### ISSUE TITLE
Cannot connect to daliserver

### ISSUE THREAD

**Issue by drmilton** [onitake/daliserver#18]
Installed on a raspberry pi 3, as per instructions. Everything seemed fine, and the service is running. But can't seem to connect. I've tried everything I can think of for ip address and port, and keep getting messages like:
   Can't connect to 127.0.0.1:55825 at usbdali.pm line 72

Using a debugger, the low-level connect function in IO/Socket.pm is saying "Connection refused".

Your help will be greatly appreciated!!
Thanks

**Comment by drmilton** [comment]
Note: The service status is always "Active (exited)", even after reboot or restart.

**Comment by drmilton** [comment]
Note

**Comment by drmilton** [comment]
Note: the service status is always "Active (exited)", even after reboot or restart

**Comment by onitake** [comment]
Please start daliserver directly and see if it finds the USB adapter.

**Comment by onitake** [comment]
Looks like daliserver binary was not built/installed correctly, so the init service failed (obviously).
Closing this bug.
