### ISSUE TITLE
Wrong month shown in daliserver log

### ISSUE THREAD

**Issue by sde1000** [onitake/daliserver#21]
This is very odd!  (But apparently harmless.)

The log entries from daliserver are being made with the wrong month.  Year, day and time are all correct.  An example from `/var/log/daliserver.log` today:
```
[2019-02-28 13:09:39] INFO Starting daliserver
[2019-02-28 13:09:39] INFO Kernel driver is active, trying to detach
[2019-02-28 13:09:39] INFO Server ready, waiting for events
```
daliserver was started with the command line `/usr/bin/daliserver -l 172.30.54.65 -f /var/log/daliserver.log -u 2:7`

**Comment by onitake** [comment]
Ouch!
RTFM would have helped.

I'm using `localtime_r` to format the date: https://github.com/onitake/daliserver/blob/master/lib/log.c#L69-L70
```
			localtime_r(&now, &nowtm);
			snprintf(datefmt, 32, "[%d-%02d-%02d %02d:%02d:%02d] ", nowtm.tm_year + 1900, nowtm.tm_mon, nowtm.tm_mday, nowtm.tm_hour, nowtm.tm_min, nowtm.tm_sec);
```

And the manual page says:
```
               int tm_mday;   /* Day of the month (1-31) */
               int tm_mon;    /* Month (0-11) */
               int tm_year;   /* Year - 1900 */
```
The year is 1900-based, the day 1-based and the month 0-based. Very consistent...
