### ISSUE TITLE
Tridonic BM RS-232 with USB adapter

### ISSUE THREAD

**Issue by CGMLab** [onitake/daliserver#9]
Hello,
First of all, thank you for maintaining this awesome library. It really is great. I've just got one small problem.

I'm using a Tridonic BM RS-232 (which is is usually through serial) plugged into a RS-232 to USB adapter in hopes of using this library. Unfortunately, the daliserver library can't seem to find it no matter what I try. 

However, the official DALI Tool finds it and operates it perfectly fine. I'm just curious if you have any input or advice on this. Thanks!

**Comment by sde1000** [comment]
The BM RS-232 is a completely different device to the DALI-USB.  daliserver doesn't have any code in it to drive it.

It's likely that the BM RS-232 is using the same serial protocol as the RS-232 PS/S.  This is documented in the data sheet - [see the link here](http://www.tridonic.com/com/en/download/data_sheets/DALI_RS232_Interface_en.pdf).  The protocol looks quite straightforward, so writing a driver ought to be fairly simple.  What kind of software do you want to use it with?

**Comment by CGMLab** [comment]
I'm writing a simple voice controlled system to control the lighting in a media studio. Unfortunately, I'm simply a first year student in a computer science major so I'm very inexperienced when it comes to these things. 

I'll look into the link you gave me and if push comes to shove, we'll just buy the Tridonic USB Dali. Thanks!

**Comment by sde1000** [comment]
I've written an outline of a driver for the RS-232 device for use with the python-dali library.  [See the file dali/serial.py in the "serialdriver" branch here.](https://github.com/sde1000/python-dali/tree/serialdriver)  Note that I don't have one of these, the code is completely untested, and I haven't included any code to handle unexpected responses from the device - that's up to you to do!

**Comment by TheAtomicNord** [comment]
Wow thanks a lot! I'll give this a shot as soon as I can!

**Comment by onitake** [comment]
@CGMLab I'm going to close this issue now, as it's out of focus of daliserver. Perhaps I'll look into supporting the RS-232 protocol in the future, but I currently don't have access to the corresponding hardware.
